name: mirror

on:
  push:
    branches:
      - "master"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace urls
        run: |
          sed -i -E 's|https://raw\.githubusercontent\.com/Wynntils/WynntilsWebsite-API/[0-9a-z]+|https://bitbucket.org/wynntils/WynntilsWebsite-API/raw/HEAD|g' urls.json maps/maps.json
          sed -i -E 's|https://raw\.githubusercontent\.com/Wynntils/Reference/[0-9a-z]+|https://bitbucket.org/wynntils/Reference/raw/HEAD|g' urls.json

      - name: Git
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global push.default simple
          git add .
          git commit -m “Mirror”
          git remote add Bitbucket https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}@bitbucket.org/wynntils/wynntilswebsite-api
          git fetch --unshallow
          git push -f Bitbucket master
